version: "3"
services:
  ying-nav-client-app-main:
    build:
      context: .
      dockerfile: docker-ying-nav-client.Dockerfile
    ports:
      - 4000:80
  ying-nav-client-app-test:
    build:
      context: .
      dockerfile: docker-ying-nav-client.Dockerfile
    ports:
      - 3000:80