name: Production

# 执行 CI 的时机: 当 git push 到 master 分支时
on:
  push:
    branches:    
      - main

# 执行所有的 jobs
jobs:
  deploy:
    # 该 Job 在自建的 Runner 中执行
    runs-on: self-hosted
    steps:
      # 切出代码，使用该 Action 将可以拉取最新代码
      - uses: actions/checkout@v2
      - name: Deploy
        run: docker-compose up -d --build ying-nav-client-app-main
      - name: Clear
        run: docker rmi $(docker images -f "dangling=true" -q)