name: Production

# 执行 CI 的时机: 当 git push 到 master 分支时
on:
  push:
    branches:    
      - test

# 执行所有的 jobs
jobs:
  deploy:
    # 该 Job 在自建的 Runner 中执行
    runs-on: self-hosted
    steps:
      - run: cd /root/ying-nav-client
      - run: git checkout test
      - run: git pull
      - name: Deploy
        run: docker-compose up -d --build ying-nav-client-app-test
      - name: Clear
        run: docker rmi $(docker images -f "dangling=true" -q)